# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/software/tools/cmake/2.8.12/bin/cmake

# The command to remove a file.
RM = /opt/software/tools/cmake/2.8.12/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/software/tools/cmake/2.8.12/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tah09e/code/workspace/lavaflow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tah09e/code/workspace/lavaflow/build

# Include any dependencies generated for this target.
include libsrc/Math/CMakeFiles/LAVAMATH.dir/depend.make

# Include the progress variables for this target.
include libsrc/Math/CMakeFiles/LAVAMATH.dir/progress.make

# Include the compile flags for this target's objects.
include libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o: libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make
libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o: ../libsrc/Math/dot.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tah09e/code/workspace/lavaflow/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/LAVAMATH.dir/dot.cxx.o -c /home/tah09e/code/workspace/lavaflow/libsrc/Math/dot.cxx

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/LAVAMATH.dir/dot.cxx.i"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tah09e/code/workspace/lavaflow/libsrc/Math/dot.cxx > CMakeFiles/LAVAMATH.dir/dot.cxx.i

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/LAVAMATH.dir/dot.cxx.s"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tah09e/code/workspace/lavaflow/libsrc/Math/dot.cxx -o CMakeFiles/LAVAMATH.dir/dot.cxx.s

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.requires:
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.provides: libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.requires
	$(MAKE) -f libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.provides.build
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.provides

libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.provides.build: libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o: libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make
libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o: ../libsrc/Math/cross.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tah09e/code/workspace/lavaflow/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/LAVAMATH.dir/cross.cxx.o -c /home/tah09e/code/workspace/lavaflow/libsrc/Math/cross.cxx

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/LAVAMATH.dir/cross.cxx.i"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tah09e/code/workspace/lavaflow/libsrc/Math/cross.cxx > CMakeFiles/LAVAMATH.dir/cross.cxx.i

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/LAVAMATH.dir/cross.cxx.s"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tah09e/code/workspace/lavaflow/libsrc/Math/cross.cxx -o CMakeFiles/LAVAMATH.dir/cross.cxx.s

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.requires:
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.provides: libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.requires
	$(MAKE) -f libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.provides.build
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.provides

libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.provides.build: libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o: libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make
libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o: ../libsrc/Math/legendre.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tah09e/code/workspace/lavaflow/build/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/LAVAMATH.dir/legendre.cxx.o -c /home/tah09e/code/workspace/lavaflow/libsrc/Math/legendre.cxx

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/LAVAMATH.dir/legendre.cxx.i"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tah09e/code/workspace/lavaflow/libsrc/Math/legendre.cxx > CMakeFiles/LAVAMATH.dir/legendre.cxx.i

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/LAVAMATH.dir/legendre.cxx.s"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tah09e/code/workspace/lavaflow/libsrc/Math/legendre.cxx -o CMakeFiles/LAVAMATH.dir/legendre.cxx.s

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.requires:
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.provides: libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.requires
	$(MAKE) -f libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.provides.build
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.provides

libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.provides.build: libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o: libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make
libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o: ../libsrc/Math/sphericalHarmonic.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tah09e/code/workspace/lavaflow/build/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o -c /home/tah09e/code/workspace/lavaflow/libsrc/Math/sphericalHarmonic.cxx

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.i"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tah09e/code/workspace/lavaflow/libsrc/Math/sphericalHarmonic.cxx > CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.i

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.s"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tah09e/code/workspace/lavaflow/libsrc/Math/sphericalHarmonic.cxx -o CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.s

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.requires:
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.provides: libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.requires
	$(MAKE) -f libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.provides.build
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.provides

libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.provides.build: libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o: libsrc/Math/CMakeFiles/LAVAMATH.dir/flags.make
libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o: ../libsrc/Math/factorial.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tah09e/code/workspace/lavaflow/build/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/LAVAMATH.dir/factorial.cxx.o -c /home/tah09e/code/workspace/lavaflow/libsrc/Math/factorial.cxx

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/LAVAMATH.dir/factorial.cxx.i"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tah09e/code/workspace/lavaflow/libsrc/Math/factorial.cxx > CMakeFiles/LAVAMATH.dir/factorial.cxx.i

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/LAVAMATH.dir/factorial.cxx.s"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tah09e/code/workspace/lavaflow/libsrc/Math/factorial.cxx -o CMakeFiles/LAVAMATH.dir/factorial.cxx.s

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.requires:
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.provides: libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.requires
	$(MAKE) -f libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.provides.build
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.provides

libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.provides.build: libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o

# Object files for target LAVAMATH
LAVAMATH_OBJECTS = \
"CMakeFiles/LAVAMATH.dir/dot.cxx.o" \
"CMakeFiles/LAVAMATH.dir/cross.cxx.o" \
"CMakeFiles/LAVAMATH.dir/legendre.cxx.o" \
"CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o" \
"CMakeFiles/LAVAMATH.dir/factorial.cxx.o"

# External object files for target LAVAMATH
LAVAMATH_EXTERNAL_OBJECTS =

libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/build.make
libsrc/Math/libLAVAMATH.a: libsrc/Math/CMakeFiles/LAVAMATH.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX static library libLAVAMATH.a"
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && $(CMAKE_COMMAND) -P CMakeFiles/LAVAMATH.dir/cmake_clean_target.cmake
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/LAVAMATH.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
libsrc/Math/CMakeFiles/LAVAMATH.dir/build: libsrc/Math/libLAVAMATH.a
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/build

libsrc/Math/CMakeFiles/LAVAMATH.dir/requires: libsrc/Math/CMakeFiles/LAVAMATH.dir/dot.cxx.o.requires
libsrc/Math/CMakeFiles/LAVAMATH.dir/requires: libsrc/Math/CMakeFiles/LAVAMATH.dir/cross.cxx.o.requires
libsrc/Math/CMakeFiles/LAVAMATH.dir/requires: libsrc/Math/CMakeFiles/LAVAMATH.dir/legendre.cxx.o.requires
libsrc/Math/CMakeFiles/LAVAMATH.dir/requires: libsrc/Math/CMakeFiles/LAVAMATH.dir/sphericalHarmonic.cxx.o.requires
libsrc/Math/CMakeFiles/LAVAMATH.dir/requires: libsrc/Math/CMakeFiles/LAVAMATH.dir/factorial.cxx.o.requires
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/requires

libsrc/Math/CMakeFiles/LAVAMATH.dir/clean:
	cd /home/tah09e/code/workspace/lavaflow/build/libsrc/Math && $(CMAKE_COMMAND) -P CMakeFiles/LAVAMATH.dir/cmake_clean.cmake
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/clean

libsrc/Math/CMakeFiles/LAVAMATH.dir/depend:
	cd /home/tah09e/code/workspace/lavaflow/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/tah09e/code/workspace/lavaflow /home/tah09e/code/workspace/lavaflow/libsrc/Math /home/tah09e/code/workspace/lavaflow/build /home/tah09e/code/workspace/lavaflow/build/libsrc/Math /home/tah09e/code/workspace/lavaflow/build/libsrc/Math/CMakeFiles/LAVAMATH.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : libsrc/Math/CMakeFiles/LAVAMATH.dir/depend

